### ISSUE TITLE
Getting 'UNRESOLVABLE_REFERENCE' Error even though the definition is present in the swagger spec

### ISSUE THREAD

**Issue by amarzavery** [apigee-127/sway#126]
## Output

```
{ errors:
   [ { code: 'INVALID_RESPONSE_BODY',
       errors:
        [ { code: 'UNRESOLVABLE_REFERENCE',
            params: [ '#/definitions/RouteFilter' ],
            message: 'Reference could not be resolved: #/definitions/RouteFilter',
            path: [] } ],
       message: 'Invalid body: Reference could not be resolved: #/definitions/RouteFilter',
       path: [] } ],
  warnings: [] }
###########################################################
.....Printing the important parts of operation object for reference...........
###########################################################

operation.responseObjects[0].definitionFullyResolved.schema: { '$ref': '#/definitions/RouteFilter' }

operation.definitionFullyResolved.responses['200'].schema: { '$ref': '#/definitions/RouteFilter' }
```

- The definition "RouteFilter" is actually present in the definitions section of the spec. It can be seen over [here](https://gist.github.com/amarzavery/0a27e2bb3558ed3ef81744ed9c3fa5a3#file-spec-json-L1272).
-  I have debugged this to the point where [`helper.validateAgainstSchema(validator, schema, value)`](https://github.com/apigee-127/sway/blob/master/lib/helpers.js#L443) is called. 
- The problem is that schema is not fully resolved by json-refs. Hence **z-schema validator** gives the _'UNRESOLVABLE_REFERENCE'_ error.

> **Can you please help me find out what is going on here?**

## Please run this script to verify the behavior.
```javascript
var Sway = require('sway'),
  util = require('util');

var specUrl = 'https://gist.githubusercontent.com/amarzavery/0a27e2bb3558ed3ef81744ed9c3fa5a3/raw/786f1c4245adcfe69266b8af65d79466a141c43e/spec.json';
var options = { definition: specUrl };

Sway.create(options)
  .then(function (api) {
    let operations = api.getOperations();
    let operation = operations[1];
    if (operation.operationId === 'RouteFilters_Get') {
      let responseWrapper = {
        statusCode: '200',
        body: operation['x-ms-examples']['RouteFilterGet']['responses']['200']['body'],
        headers: {
          'content-type': 'application/json'
        }
      };
      let result = operation.validateResponse(responseWrapper);
      console.dir(result, {depth: null, colors: true});
      console.log('###########################################################');
      console.log('.....Printing the operation object for reference...........')
      console.log('###########################################################\n');
      console.log('operation.responseObjects[0].definitionFullyResolved.schema: ' + util.inspect(operation.responseObjects[0].definitionFullyResolved.schema, {depth: null}));
      console.log('\noperation.definitionFullyResolved.responses[\'200\'].schema: ' + util.inspect(operation.definitionFullyResolved.responses['200'].schema, {depth: null}));
    } else {
      console.log( operation.operationId + ' is not the operation we are looking for.');
    }
  }, function (err) {
    console.error(err.stack);
  });
```

**Comment by whitlockjc** [comment]
I can confirm this.  I'll look into it.

**Comment by amarzavery** [comment]
@whitlockjc - Sorry for bugging you. But any update on this? This will be a blocker for us. We are planning to take a dependency on this in our CI process before merging swaggers.

Any update would be really helpful.


## Interesting feature in z-schema that can be used in Sway
Btw, I found another way to validate examples against model definitions. 

- z-schema provides a mechanism to validate against **sub-schemas**. In our case (as in for Sway) swagger spec is the schema and the model definition in the definitions section is the sub-scehma.

I followed the example provided in the [z-schema repo over here](https://github.com/zaggino/z-schema#validate-against-subschema).
```javascript
let valid = validator.validate(responseBodyExample, schema, { schemaPath: "definitions.RouteFilter" });
if (!valid) {
  let error = validator.getLastErrors();
  console.dir(error, {depth: null, colors: true});
}
```
where:
 - **responseBodyExample** is the _actual data_
 - **schema** is the parsed _swagger spec_
 - **schemaPath** is the _path to the model definition in the spec_ against which the sample needs to be validated

If we use this approach then one need not depend on json-refs to fullyResolve references. It makes life simple when circular references are involved.

I ran the above changes locally in my script and it did the right thing for me. 

What do you  think about it?

**Comment by amarzavery** [comment]
@whitlockjc - Any thoughts on the alternative approach (z-schema feature _"validating against a sub-schema"_) provided in the previous comment?

**Comment by whitlockjc** [comment]
I implemented that at one point honestly and it worked fine but I needed the full schema to generate sample data anyways so I just went with one approach.  The fully-resolved approach should _just work_ once the `json-refs` bugs are fixed.  A complete rewrite of the `json-refs` resolver is almost done and it should fix all bugs and performance issues brought up in the past.  I just need a little more time.

**Comment by amarzavery** [comment]
I see. No worries. I have forked your repo and made changes based on the alternate solution. I am testing different scenarios to make sure everything works. Once things look good, will send a PR. Would love to take your feedback on it :).

**Comment by whitlockjc** [comment]
Did a PR ever come from this?

**Comment by whitlockjc** [comment]
With the latest on `master`, `json-refs` has been updated and should be fully-resolving everything.  Is this still an issue?

**Comment by whitlockjc** [comment]
Closing this until there is more information.

**Comment by drej1** [comment]
Hi @whitlockjc just one question! I'm dealing with this same issue. it's fine that it is fixed in master, but how can I tell to my node.js application to use sway from master? I can only tell to use version 1.0.0 which doesn't include this fix. Will there be soon, I mean very soon some new release? Thanks

**Comment by whitlockjc** [comment]
You can use `npm install --save apigee-127/sway#master`.

**Comment by drej1** [comment]
Thanks! My fault, didn't check npm documentation in detail :/

**Comment by drej1** [comment]
Hi @whitlockjc I still have a problem with **UNRESOLVABLE_REFERENCE**.
I have the following swagger model defined:
``` yaml
CategoryModel:
    type: object
    properties:
      _id:
        type: string
        description: category name (id)
      displayName:
       type: string
       description: category display name
      imgUrl:
        type: string
        description: category image url
      parent:
        $ref: "#/definitions/CategoryModel"
      ancestors:
        type: array
        items: 
          $ref: "#/definitions/CategoryModel"
```

While sending a request I get the following error:
``` json
{
  "code": "INVALID_REQUEST_PARAMETER",
  "errors": [
    {
      "code": "UNRESOLVABLE_REFERENCE",
      "params": [
        "#/definitions/CategoryModel"
      ],
      "message": "Reference could not be resolved: #/definitions/CategoryModel",
      "path": [
        "properties",
        "ancestors",
        "items"
      ]
    },
    {
      "code": "UNRESOLVABLE_REFERENCE",
      "params": [
        "#/definitions/CategoryModel"
      ],
      "message": "Reference could not be resolved: #/definitions/CategoryModel",
      "path": [
        "properties",
        "parent"
      ]
    }
  ],
  "in": "body",
  "message": "Invalid parameter (CategoryModel): Value failed JSON Schema validation",
  "name": "CategoryModel",
  "path": [
    "paths",
    "/categories",
    "post",
    "parameters",
    "0"
  ]
}
```

Please could you take a look at it what am I missing?
Thank you very much!

**Comment by whitlockjc** [comment]
I'll need more information.  What I see suggests there is no issue but I've no idea what you document(s) structure looks like.

**Comment by drej1** [comment]
Here's my whole swagger.yaml
[swagger.zip](https://github.com/apigee-127/sway/files/1666850/swagger.zip)

And I'm sending the following documents in body:
example1:
``` json
{
  "_id": "cat1"
}
```

example2:
``` json
{
  "_id": "cat2",
  "parent": {
    "_id": "cat1"
  }
}
```

**Comment by whitlockjc** [comment]
Can you tell me how the document is being used?  If I validate the document, it validates without error.  Are you using some APIs that might not be working properly?

**Comment by drej1** [comment]
I use swagger-node with updated swagger-node-runner and swagger-express-mw and sway.
It fails in my tests while sending request to the swagger-node endpoint via superagent.
Does this help?

This week I will try to debug the process if this doesn't help.
Thanks

**Comment by whitlockjc** [comment]
`swagger-node-runner` uses an old version of `json-refs` which had issues.  But in all honesty, I'm not sure how `sway` is being used so it's hard to tell.  It seems like you're validating a request which means `sway` isn't fully resolving documents _(fixed in `json-refs@v3.0.0+`)_ or `sway` is using the wrong schema _(the not-fully-resolved one)_.  Without a reproduction recipe, it will be hard to fix since I cannot reproduce it.

**Comment by drej1** [comment]
Hi, I found the issue:)
In sway you are calling `helpers.removeCirculars(results.definitionFullyResolved);` while the removeCirculars function assumes the definition is fully resolved but it is not, because json-refs is not called with option `resolveCirculars=true` and by default it is set to `false`, so the circulars are detected but not resolved. This way there are no repeating nodes inside `removeCirculars` function, nothing is replaces with `{}`. Please can you fix sway to call json-refs with `resolveCirculars=true` option?

Or maybe change the logic of the `removeCirculars` method to use json-refs's `circular=true` flag even when the circulars are not resolved?

Thanks.

**Comment by whitlockjc** [comment]
I'll file a new issue.  If you haven't seen it by the time you read this, feel free to do the same.

**Comment by drej1** [comment]
Hi, thanks. I filed issue #165

**Comment by whitlockjc** [comment]
You can already use `options.jsonRefs` in [Sway.create(options)](https://github.com/apigee-127/sway/blob/master/docs/API.md#swaycreateoptions--promise) to alter how `json-refs` is invoked.  But the reason `sway` isn't released with proper `json-refs@v3.0.0+` support is because of things like this.

**Comment by amarzavery** [comment]
Sway is a fantastic library for doing different swagger validations. However, in the initial days I had several issues with resolving json reference around relative paths or circular references. I ended up writing my swagger spec resolver such that all the references are local to the document. I then give the resolved swagger to sway for doing semantic and model validation. After that everything works like a charm.
You can take a look at my project over here http://github.com/azure/oav.

You can use the command `oav resolve -spec <spec-path> [optional parameters]` and then give that resolved spec to sway as an input.

**Comment by amarzavery** [comment]
Precursor:

> Sway is an awesome tool. We absolutely love it and use it everyday for validating our swaggers. Kudos to @whitlockjc for building such an awesome tool. Many thanks for all the hard work!!

There are couple of other issues that I had with sway. Listing them over here in the hope that this helps other people who might have encountered similar issues.

## Validating polymorphic models
 It does not correctly validate polymorphic models. For example `Cat` and `Dog` are having an `allOf` relationship with `Animal` which has a discriminator property named `dtype`, then at runtime the request body or the response body could be an `Animal` or a `Cat` or a `Dog`. If the model specified was a `Cat` then sway would not fail if some required properties of `Cat` were not provided. I have solved that issue in my tool.

Basically, one need to add `"additionalProperties": false` on all the models that do not have any additionalProperties set. This makes their json schemas stricter. Now if any unknown property is given the validator will fail. On top of that I have changed all the polymorphic models to be a `oneOf` the `parent` model or `it's children`. Thus when this is given to `z-schema` validator (package on which `sway` depends for model validation), it does a crisp job of validating polymorphic types.

## Validating nullable types
There are services that reuse the same model in request body and response body. At times the model has a sensitive property like `password` or `storageAccountSecret` that is required while the model is being used as in the request body and when the service sends the same model back in the response, it sets those sensitive properties with a `null` value. Now `sway` will fail with an error `null is not a valid "string" type`. This is theoretically correct, but it is a noise in the current context. Hence I added support for resolving nullable types in my tool. Many people in the swagger community support `"x-nullable": true` as  an extension in their tool chain. So we have added support for that.

**Comment by whitlockjc** [comment]
I'm not sure this is the proper way to address concerns.  I'd rather see issues that can be fixed than discussing things in one issue about other issues.  Also, `json-refs`' issues that you mentioned about resolving references should be fixed.

**Comment by amarzavery** [comment]
Sure. I shall open separate issues.

**Comment by amarzavery** [comment]
I have opened :
- #169 (validating polymorphic types)
- #170 (validating nullable types) as separate issues as directed. Thank you :).

**Comment by penx** [comment]
I'm getting this issue at the moment and am trying to debug to get more info for you.

From what I can tell, it's from the following lines:

https://github.com/apigee-127/sway/blob/ee8329540b4c1a279c5077a6937bcd495f085b89/lib/types/parameter-value.js#L122-L125

The call to `validateAgainstSchema` passes `parameterObject.schema`, which is only a subset of the schema and doesn't contain the `#/definitions` node.

**Comment by penx** [comment]
this is with swagger-node-runner@0.7.3, sway@master and json-refs@3.0.4

I'm not sure whether you're saying above that `parameterObject.schema` should not contain any references ($ref keys) as these should be fully resolved by json-refs before calling`validateAgainstSchema`?

In which case I guess the issue I'm having is with swagger-node-runner (the call to operation:validateRequest from fittings/swagger_validator) as it should be passing in an already resolved schema for the parameter but is not.

**Comment by penx** [comment]
would it help if I create an example that reproduces this?

**Comment by whitlockjc** [comment]
`Parameter.schema` should be fully-resolved and based on the code, that is the case.  If you're using `sway@v1.0.0`, it is possible that a `json-refs` issue is causing the problem.  If you're using `sway@master`, you might want to file a bug with a reproduction recipe.

**Comment by whitlockjc** [comment]
Since you mention `swagger-node-runner`, I'm assuming you're using a version of `sway` less than `v1.0.0` and most certainly less than `master`.  So I am not surprised you're running into a situation where the document isn't fully resolved.

**Comment by penx** [comment]
I’m using a fork of swagger node runner and am using sway@master

**Comment by whitlockjc** [comment]
Then I'll need to know more about the reproduction.  `json-refs` resolver, the one being used in `sway@master`, doesn't have any resolution issues I'm aware of but there were some things it use to resolve that it shouldn't had and that _could_ be related.

**Comment by penx** [comment]
After writing the example, I am pretty sure it's the same as issue #165
